version: '3'

services:

 db:
    image: postgres:9.6
    hostname: postgres
    networks:
      - test
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: "awx"
      POSTGRES_PASSWORD: "awxpass"
      POSTGRES_DB: "awx"
    deploy:
      placement:
        constraints: [node.role == manager]

 mq:
   image: rabbitmq:3
   hostname: rabbit
   networks:
      - test
   ports:
     - 5672:5672
     - 15672:15672
   environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
   depends_on:
       - db
   deploy:
      placement:
        constraints: [node.role == manager]


 mem:
   image: memcached:alpine
   hostname: memcache
   networks:
      - test
   ports:
    - 11211:11211
   depends_on:
       - mq
       - db
   deploy:
      placement:
        constraints: [node.role == manager]


 web:
    image: ansible/awx_web:1.0.0
    hostname: awxweb
    networks:
      - test
    user: root
    ports:
        - 80:8052
    environment:
      SECRET_KEY: "awxsecret"
      DATABASE_NAME: "awx"
      DATABASE_USER: "awx"
      DATABASE_PASSWORD: "awxpass"
      DATABASE_PORT: "5432"
      DATABASE_HOST: "postgres"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_PORT: "5672"
      RABBITMQ_VHOST: "awx"
      MEMCACHED_HOST: "memcache"
      MEMCACHED_PORT: "11211"
      AWX_ADMIN_USER: "admin"
      AWX_ADMIN_PASSWORD: "password"
    depends_on:
       - mem
       - mq
       - db
    deploy:
      placement:
        constraints: [node.role == manager]

 task:
    image: ansible/awx_task:1.0.0
    hostname: awx
    networks:
      - test
    user: root
    environment:
      SECRET_KEY: "awxsecret"
      DATABASE_NAME: "awx"
      DATABASE_USER: "awx"
      DATABASE_PASSWORD: "awxpass"
      DATABASE_PORT: "5432"
      DATABASE_HOST: "postgres"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_PORT: "5672"
      RABBITMQ_VHOST: "awx"
      MEMCACHED_HOST: "memcache"
      MEMCACHED_PORT: "11211"
      AWX_ADMIN_USER: "admin"
      AWX_ADMIN_PASSWORD: "password"
    depends_on:
       - web
       - mem
       - mq
       - db
    deploy:
      placement:
        constraints: [node.role == manager]


networks: 
    test:
